# This is a basic workflow to help you get started with Actions

name: Build-Font

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build font (Same as .azure-pipelines.yml)
  build:
    name: Build Font
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          sudo apt-get install -y ttfautohint
          pip install -r requirements.txt ufolint
          
      - name: Lint sources
        run: ufolint sources/*.ufo
      
      # TODO: Investigate need for static fonts
      - name: Build variable fonts
        # We don't care about the mono font
        run: python ./build.py -W -M

      - name: Archive fonts
        run: |
          mkdir -p out
          cd build
          zip -r ../out/CascadiaCode.zip ttf otf woff2
          cd ..
          
      - name: Upload font artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: FontPackage
          path: out/CascadiaCode.zip
