# This is a basic workflow to help you get started with Actions

name: Build-Font

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build font (Same as .azure-pipelines.yml)
  build:
    name: Build Font
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          sudo apt-get install -y ttfautohint
          pip install -r requirements.txt ufolint
          
      - name: Lint sources
        run: ufolint sources/*.ufo
      
      # Build fonts with:
      #   - Web fonts
      #   - No mono fonts (the whole point of this is having custom ligatures)
      #   - Static fonts (Needed for NerdFont patcher)
      - name: Build fonts
        run: python ./build.py -W -M -S
          
      - name: Upload font artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: RawFonts
          path: build/
  
  patch:
    # Based on: https://github.com/adam7/delugia-code/blob/master/.github/workflows/ci.yaml
    name: Patch fonts with NerdPatcher
    runs-on: ubuntu-latest
    needs: build
    env:
      NERDFONTVERS: v2.1.0

    steps:
      - name: Setup Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
          
#       - name: Setup tmate session
#         uses: mxschmitt/action-tmate@v3
#         if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        
      - name: Install FontForge
        run: sudo apt-get install fontforge -y

      - name: Download and patch Font Patcher
        run: |
          curl -L https://raw.githubusercontent.com/ryanoasis/nerd-fonts/${NERDFONTVERS}/font-patcher --output font-patcher
          curl -L https://raw.githubusercontent.com/adam7/delugia-code/d959866015842ed0016415c0282703390e528d0c/0001-font-patcher-Use-correct-source-font-metrics.patch --output 0001.patch
          patch font-patcher 0001.patch

      - name: Download font package
        uses: actions/download-artifact@v2.0.10
        with:
          name: RawFonts
          path: build/
          
      - name: Download Source Fonts
        run: |
          bash <(curl -L https://raw.githubusercontent.com/adam7/delugia-code/d959866015842ed0016415c0282703390e528d0c/download-source-fonts.sh)
          
      - name: Extract additional powerline glyphs
        run: |
          curl -L https://raw.githubusercontent.com/adam7/delugia-code/master/extract-extra-glyphs --output extract-extra-glyphs
          fontforge -lang=ff -script extract-extra-glyphs

      - name: Patch
        run: |
          fontforge -script font-patcher --careful -c --custom SomeExtraSymbols.otf --no-progressbars "ttf/static/CascadiaCodePL-Regular.ttf" --mono | tee "process1.log"

#       - name: Build Complete
#         run: |
#           ./do_generate 21 -c --mono CascadiaCodePL-Regular.ttf            DelugiaComplete.ttf              "Delugia"       "Regular"
#           ./do_generate 22 -c --mono CascadiaCodePL-Bold.ttf               DelugiaComplete-Bold.ttf         "Delugia"       "Bold"
#           ./do_generate 23 -c --mono CascadiaCodePL-Italic.ttf             DelugiaComplete-Italic.ttf       "Delugia"       "Italic"
#           ./do_generate 24 -c --mono CascadiaCodePL-BoldItalic.ttf         DelugiaComplete-BoldItalic.ttf   "Delugia"       "Bold Italic"
#           ./do_generate 25 -c --mono CascadiaCodePL-Light.ttf              DelugiaCompleteLight.ttf         "Delugia Light" ""
#           ./do_generate 26 -c --mono CascadiaCodePL-LightItalic.ttf        DelugiaCompleteLight-Italic.ttf  "Delugia Light" "Italic"
#           mkdir delugia-complete
#           mv Delugia*ttf delugia-complete
#           zip delugia-complete.zip delugia-complete/*
#
#       - uses: actions/upload-artifact@master
#         with:
#           name: Delugia Complete
#           path: "delugia-complete"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
#         if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Upload patched font artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: PatchedFonts
          path: patched/

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        # if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
